#!/bin/sh

travis_retry go get github.com/tcnksm/ghr github.com/mitchellh/gox

go test -v ./...
RESULT=$?

echo Done tests with exit code $RESULT
if [ "$RESULT" != "0" ]; then
  return $RESULT
fi

# Test cross-compilation. The binaries produced are also used for release
# upload in after_success if this is a release tag.

echo Cross-compiling releases...
mkdir -p "$GOPATH/releasing/idist" "$GOPATH/releasing/dist"

# Assume that x86 machines don't necessarily have SSE2. Whereas for amd64,
# require SSE2.

# cgo crosscompile
REPO="github.com/$TRAVIS_REPO_SLUG"
BINARIES="$REPO"
gox -cgo -osarch 'linux/amd64' -output "$GOPATH/releasing/idist/{{.Dir}}-$TRAVIS_TAG-{{.OS}}_{{.Arch}}/bin/x" $BINARIES
RESULT1=$?
GO386=387 gox -cgo -osarch 'linux/386' -output "$GOPATH/releasing/idist/{{.Dir}}-$TRAVIS_TAG-{{.OS}}_{{.Arch}}/bin/x" $BINARIES
RESULT2=$?

# non-cgo crosscompile
gox -osarch 'darwin/amd64 linux/arm freebsd/amd64 freebsd/arm openbsd/amd64 netbsd/amd64 netbsd/arm dragonfly/amd64 solaris/amd64' -output "$GOPATH/releasing/idist/{{.Dir}}-$TRAVIS_TAG-{{.OS}}_{{.Arch}}/bin/x" $BINARIES
RESULT3=$?
GO386=387 gox -osarch 'darwin/386 freebsd/386 openbsd/386 netbsd/386' -output "$GOPATH/releasing/idist/{{.Dir}}-$TRAVIS_TAG-{{.OS}}_{{.Arch}}/bin/x" $BINARIES
RESULT4=$?

echo "cgo crosscompile (amd64) exited with code $RESULT1"
echo "cgo crosscompile (386) exited with code $RESULT2"
echo "non-cgo crosscompile (amd64, arm) exited with code $RESULT3"
echo "non-cgo crosscompile (386) exited with code $RESULT4"

if [ "$RESULT1" != "0" ]; then
  return $RESULT1
fi
if [ "$RESULT2" != "0" ]; then
  return $RESULT2
fi
if [ "$RESULT3" != "0" ]; then
  return $RESULT3
fi
if [ "$RESULT4" != "0" ]; then
  return $RESULT4
fi
